export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #fff9fd 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8fef3 0%, #f5fff8 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' },
];


export const APP_FEATURES = [
    {
        id: "01",
        title: "Role-Specific Interview Questions",
        description: "Receive interview questions and model answers tailored to your chosen role, experience level, and focus areas—no more generic prep."
    },
    {
        id: "02",
        title: "AI-Powered Explanations",
        description: "Instantly access detailed, beginner-friendly explanations for any question, generated by advanced AI to help you master concepts."
    },
    {
        id: "03",
        title: "Personal Notes & Pinning",
        description: "Add your own notes to every question and pin the most important ones to the top, keeping your learning organized and actionable."
    },
    {
        id: "04",
        title: "Session Management",
        description: "Save your interview sets, organize them in your dashboard, and easily revisit or continue your preparation anytime."
    },
    {
        id: "05",
        title: "Progress Tracking",
        description: "Monitor your preparation journey with session history and performance insights to identify strengths and areas for improvement."
    },
    {
        id: "06",
        title: "Note Taking on Every Question",
        description: "Effortlessly jot down thoughts, strategies, and reminders for each interview question, making your preparation truly personalized."
    }
];
